security:
    encoders:
        App\Entity\Hunter:
            algorithm: auto
        App\Entity\User:
            algorithm: auto

    providers:
        admin_user_provider:
            entity:
                class: App\Entity\User
                property: username
        app_user_provider:
            entity:
                class: App\Entity\Hunter
                property: uuid

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            anonymous: lazy
            provider: admin_user_provider
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Securiy\Guard\FirebaseGuardAuthenticator
            logout: ~
            provider: app_user_provider
            stateless: true
            user_checker: App\Securiy\Core\User\HunterChecker

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
