vich_uploader:
    db_driver: orm

    mappings:
        animal_image:
            uri_prefix: /images/animals
            upload_destination: '%kernel.project_dir%/public/images/animals'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
