vich_uploader:
    db_driver: orm

    mappings:
        animal_images:
            uri_prefix: '%app.path.animal_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.animal_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
