easy_admin:
    design:
        menu:
            - label: 'menu.inventory'
              icon: 'database'
              children:
                  - { entity: 'Animal', icon: 'paw', label: 'menu.animal' }
            - label: 'menu.users'
              icon: 'users'
              children:
                  - { entity: 'User', icon: 'user', label: 'menu.user' }
                  - { entity: 'Hunter', icon: 'walking', label: 'menu.hunter' }
