name: test-integration
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"
            - uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-
            - name: Init environment
              run: cd support/docker && ./init-test.sh
            - name: Run tests
              run: ./support/docker/composer.sh check
              env:
                  SYMFONY_ENV: test
            - name: Show log on failure
              if: failure()
              run:  |
                  cd support/docker && docker-compose exec -T php-fpm.readid.stepup.example.com cat var/logs/test/test.log
